version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      args:
        RUNTIME: ${FRONTEND_RUNTIME}
