version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      args:
        RUNTIME: win-x64
    volumes:
      - ./output:/app/publish
    command: dotnet publish -c Release -r win-x64 --self-contained false -o /app/publish

