-- -- Tạo CDB và PDB 
-- Chuyển vào PDB:
-- BEGIN
--   EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE QLNhanVien CLOSE IMMEDIATE';
--   EXECUTE IMMEDIATE 'DROP PLUGGABLE DATABASE QLNhanVien INCLUDING DATAFILES';
-- EXCEPTION
--   WHEN OTHERS THEN NULL; -- Bỏ qua nếu PDB không tồn tại
-- END;
-- /

-- CREATE PLUGGABLE DATABASE QLNhanVien
--   ADMIN USER admin IDENTIFIED BY 123456
--   ROLES = (DBA)
--   FILE_NAME_CONVERT = ('/opt/oracle/oradata/FREE/pdbseed', '/opt/oracle/oradata/QLNhanVien/');
-- /

-- Mở PDB vừa tạo
-- ALTER PLUGGABLE DATABASE QLNhanVien OPEN;

-- Gán tablespace SYSTEM quota cho user admin (phải ALTER trong PDB context)
ALTER SESSION SET CONTAINER = QLNhanVien;
ALTER USER admin QUOTA UNLIMITED ON SYSTEM;

GRANT CREATE USER, ALTER USER, DROP USER TO ADMIN;
GRANT SYSDBA TO admin;
GRANT GRANT ANY PRIVILEGE TO admin;
GRANT CREATE ROLE TO ADMIN;


GRANT UNLIMITED TABLESPACE TO ADMIN;

CREATE TABLESPACE USERS
  DATAFILE '/opt/oracle/oradata/QLNHANVIEN/users.dbf'
  SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

-- ALTER PLUGGABLE DATABASE QLNhanVien OPEN;
-- SELECT name, open_mode FROM v$pdbs;

-- ALTER SESSION SET CONTAINER=CDB$ROOT;
-- SELECT NAME, OPEN_MODE FROM V$PDBS;
-- Sau đó chuyển sang user ADMIN:

-- GRANT CONNECT TO admin;
-- CREATE TABLESPACE USER_TBS
--     DATAFILE '/opt/oracle/oradata/QLNhanVien/user_tbs01.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CONNECT admin/123456@localhost:1521/QLNhanVien;



-- Bảng DONVI
CREATE TABLE DONVI (
    MADV VARCHAR2(10) PRIMARY KEY,
    TENDV VARCHAR2(100),
    LOAIDV VARCHAR2(20),
    TRGDV VARCHAR2(10) 
);
-- MADV: HOA => TENDV: Khoa hoá học => LOAIDV: KHOA
-- MADV PDT => TENDV: Phòng đào tạo => LOAIDV: PHONG

-- Bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANV VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    PHAI CHAR(1), -- 1: male, 0: female
    NGSINH DATE,
    LUONG NUMBER, 
    PHUCAP NUMBER,
    DT VARCHAR2(15),
    VAITRO VARCHAR2(50),
    MADV VARCHAR2(10), 
    FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);
ALTER TABLE DONVI ADD FOREIGN KEY (TRGDV) REFERENCES NHANVIEN(MANV);
ALTER TABLE NHANVIEN ADD CONSTRAINT CS_NHANVIEN_PHAI CHECK (PHAI IN ('1', '0'));
-- NHANVIEN: VAITRO
-- NVCB: 500
-- GV: 200
-- NV PDT: 20
-- NV PKT: 10
-- NV TCHC: 15
-- NV CTSV: 10
-- TRGDV: 15

-- Bảng SINHVIEN
CREATE TABLE SINHVIEN (
    MASV VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    PHAI CHAR(1),
    NGSINH DATE,
    DCHI VARCHAR2(256), 
    DT VARCHAR2(15),
    KHOA VARCHAR2(10),
    TINHTRANG VARCHAR2(100)
);
ALTER TABLE SINHVIEN ADD CONSTRAINT CS_SINHVIEN_PHAI CHECK (PHAI IN ('1', '0'));
-- NHANVIEN: 4000
ALTER TABLE SINHVIEN
MODIFY TINHTRANG VARCHAR2(100);
-- Bảng HOCPHAN
CREATE TABLE HOCPHAN (
    MAHP VARCHAR2(10) PRIMARY KEY,
    TENHP VARCHAR2(100),
    SOTC NUMBER,
    STLT NUMBER,
    STTH NUMBER,
    MADV VARCHAR2(10),
    FOREIGN KEY (MADV) REFERENCES DONVI(MADV)
);

-- Bảng MOMON
CREATE TABLE MOMON (
    MAMM VARCHAR2(10) PRIMARY KEY,
    MAHP VARCHAR2(10),
    MAGV VARCHAR2(10),
    HK NUMBER,
    NAM NUMBER,
    FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP),
    FOREIGN KEY (MAGV) REFERENCES NHANVIEN(MANV)
);

-- Bảng DANGKY
CREATE TABLE DANGKY (
    MASV VARCHAR2(20),
    MAMM VARCHAR2(10),
    DIEMTH NUMBER,
    DIEMQT NUMBER,
    DIEMCK NUMBER,
    DIEMTK NUMBER,
    PRIMARY KEY (MASV, MAMM),
    FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    FOREIGN KEY (MAMM) REFERENCES MOMON(MAMM)
);
-- DIEMTK: => DIEMQT*20% + DIEMTH*30% + DIEMCK*50%

