-- CREATE TABLE DONVI (
--     MADV VARCHAR2(10) PRIMARY KEY,
--     TENDV VARCHAR2(100),
--     LOAIDV VARCHAR2(20),
--     TRGDV VARCHAR2(10) 
-- );
-- MADV: HOA => TENDV: Khoa hoá học => LOAIDV: KHOA
-- MADV PDT => TENDV: Phòng đào tạo => LOAIDV: PHONG
CONNECT admin/123456@localhost:1521/QLNHANVIEN;

INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('PDT', 'Phòng đào tạo', 'PHONG');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('PKT', 'Phòng kế toán', 'PHONG');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('CTSV', 'Phòng công tác sinh viên', 'PHONG');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('TOAN', 'Khoa Toán học', 'KHOA');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('VATLY', 'Khoa Vật lý', 'KHOA');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('CNTT', 'Khoa Công nghệ thông tin', 'KHOA');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('HOA', 'Khoa Hoá học', 'KHOA');
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('KHKT', 'Khoa kỹ thuật', 'KHOA');  
INSERT INTO DONVI(MADV, TENDV, LOAIDV) VALUES ('SINH', 'Khoa Sinh học', 'KHOA');
-- SINHVIEN: csv
-- NHANVIEN

-- HOCPHAN
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00003', 'Vi tích phân 1B', 3, 45, 0, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00081', 'Thực hành Vi tích phân 1B', 1, 0, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00004', 'Vi tích phân 2B', 3, 45, 0, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00082', 'Thực hành Vi tích phân 2B', 1, 0, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00030', 'Đại số tuyến tính', 3, 45, 0, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00083', 'Thực hành Đại số tuyến tính', 1, 0, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00040', 'Xác xuất thống kê', 3, 45, 0, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00085', 'Thực hành Xác xuất thống kê', 1, 0, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00041', 'Toán rời rạc', 3, 45, 0, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00086', 'Thực hành Toán rời rạc', 1, 0, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00050', 'Toán học tổ hợp', 4, 45, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00051', 'Toán ứng dụng và thống kê', 4, 45, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00052', 'Phương pháp tính', 4, 45, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00053', 'Lý thuyết số', 4, 45, 30, 'TOAN');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('MTH00054', 'Phép tính vị từ', 4, 45, 30, 'TOAN');


INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('PHY00001', 'Vật lý đại cương 1', 3, 30, 0, 'VATLY');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('PHY00002', 'Vật lý đại cương 2', 3, 30, 0, 'VATLY');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('PHY00081', 'Thực hành Vật lý đại cương 1', 2, 0, 60, 'VATLY');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('PHY00082', 'Thực hành Vật lý đại cương 2', 2, 0, 60, 'VATLY');

INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('BIO00001', 'Sinh đại cương 1', 3, 30, 0, 'SINH');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('BIO00002', 'Sinh đại cương 2', 3, 30, 0, 'SINH');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('BIO00081', 'Thực hành Sinh đại cương 1', 2, 0, 60, 'SINH');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('BIO00082', 'Thực hành Sinh đại cương 2', 2, 0, 60, 'SINH');

INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10001', 'Nhập môn lâp trình', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10002', 'Kỹ thuật lập trình', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10003', 'Phương pháp lập trình hướng đối tượng', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10004', 'Cấu trúc dữ liệu và giải thuật', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10006', 'Cơ sở dữ liệu', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10007', 'Hệ điều hành', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10008', 'Mạng máy tính', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC10009', 'Hệ thống máy tính', 2, 30, 0, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC13002', 'Nhập môn công nghệ phần mềm', 4, 45, 30, 'CNTT');
INSERT INTO HOCPHAN(MAHP, TENHP, SOTC, STLT, STTH, MADV) VALUES ('CSC14003', 'Cơ sở trí tuệ nhân tạo', 4, 45, 30, 'CNTT');

